import os

SERVER_HOST         = os.getenv("SERVER_HOST", "127.0.0.1")
SERVER_PORT         = int(os.getenv("SERVER_PORT", "8888"))
PROB_BUY            = int(os.getenv("PROB_BUY", "30"))
PROB_SELL           = int(os.getenv("PROB_SELL", "30"))
PROB_CANCEL         = int(os.getenv("PROB_CANCEL", "10"))
PROB_MARKET_BUY     = int(os.getenv("PROB_MARKET_BUY", "15"))
PROB_MARKET_SELL    = int(os.getenv("PROB_MARKET_SELL", "15"))
ASSET_INITIAL_PRICE = int(os.getenv("ASSET_INITIAL_PRICE", "150"))
STD_DEV             = float(os.getenv("std_dev", "0.5"))
SLEEP_TIMEOUT       = int(os.getenv("SLEEP_TIMEOUT", "2"))
NUM_BOTS            = int(os.getenv("NUM_BOTS", "10"))
TELEMETRY_HOST      = os.getenv("TELEMETRY_HOST", "localhost")
TELEMETRY_PORT      = int(os.getenv("TELEMETRY_PORT", "8125"))
